USERDOMAIN=DESKTOP-A0KO5F9
OS=Windows_NT
COMMONPROGRAMFILES=C:\Program Files\Common Files
PROCESSOR_LEVEL=6
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
CommonProgramW6432=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
LANG=en_US.UTF-8
platformcode=KV
PUBLIC=C:\Users\Public
EXEPATH=C:\Program Files\Git\bin
OnlineServices=Online Services
USERNAME=jdavi
LOGONSERVER=\\DESKTOP-A0KO5F9
PROCESSOR_ARCHITECTURE=AMD64
LOCALAPPDATA=C:\Users\jdavi\AppData\Local
COMPUTERNAME=DESKTOP-A0KO5F9
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
SYSTEMDRIVE=C:
USERPROFILE=C:\Users\jdavi
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
SYSTEMROOT=C:\WINDOWS
USERDOMAIN_ROAMINGPROFILE=DESKTOP-A0KO5F9
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
OneDriveConsumer=C:\Users\jdavi\OneDrive
PWD=/c/Users/jdavi/Post DevMtn/python-workshop
HOME=/c/Users/jdavi
TMP=/tmp
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.33.1
OneDrive=C:\Users\jdavi\OneDrive
PROCESSOR_REVISION=8e0a
FPS_BROWSER_USER_PROFILE_STRING=Default
NUMBER_OF_PROCESSORS=8
ProgramW6432=C:\Program Files
COMSPEC=C:\WINDOWS\system32\cmd.exe
APPDATA=C:\Users\jdavi\AppData\Roaming
TERM=cygwin
WINDIR=C:\WINDOWS
ProgramData=C:\ProgramData
SHLVL=1
PLINK_PROTOCOL=ssh
PROGRAMFILES=C:\Program Files
ALLUSERSPROFILE=C:\ProgramData
TEMP=/tmp
DriverData=C:\Windows\System32\Drivers\DriverData
MSYSTEM=MINGW64
SESSIONNAME=Console
RegionCode=NA
ProgramFiles(x86)=C:\Program Files (x86)
PATH=/mingw64/bin:/usr/bin:/c/Users/jdavi/bin:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/nodejs:/c/WINDOWS/System32/OpenSSH:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common Files/Intel/WirelessCommon:/c/Users/jdavi/AppData/Local/Microsoft/WindowsApps:/c/Users/jdavi/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/jdavi/AppData/Roaming/npm
PS1=\[\033]0;$TITLEPREFIX:$PWD\007\]\n\[\033[32m\]\u@\h \[\033[35m\]$MSYSTEM \[\033[33m\]\w\[\033[36m\]`__git_ps1`\[\033[0m\]\n$ 
HOMEDRIVE=C:
HOMEPATH=\Users\jdavi
OLDPWD=/c/Users/jdavi/Post DevMtn
_=/usr/bin/env
